name: analyze-action
on:
  pull_request:
    branches: [main, develop, develop/* ]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: dummy
      run: |
        test (0 = 0) && echo "This is a dummy test!"
